name: Bump Package Version

on:
  push:
    tags:
      - '*'

jobs:
  update-deps:
    name: Bump Node version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
